site_name: Справочник полезных знаний
theme:
  name: material
  logo: logo_big3-1.jpg
  favicon: logo_fav.jpg
  language: ru
  features: 
    - navigation.tabs
    - search.suggest
nav:
  - Главная: index.md
  - ГОСТы: 
    - Общие правила: GOST/GOST-svod.md
    - Оформление по ГОСТ 2, 19, 7.32, 7.0.97: GOST/GOST-srav.md
    - Полезная информация: GOST/GOST-dop.md
  - Документация: 
      - Перечень шаблонов: Template/Spisok.md
      - Превью шаблонов программной документации:
        - Спецификация: Template/Specifikacia.md
        - Текст программы: Template/Tekst.md
        - Описание программы: Template/Opisanie-programmi.md
        - Ведомость эксплуатационных документов: Template/VED.md
        - Формуляр: Template/Formular.md
        - Описание применения: Template/Opisanie-primenenia.md
        - Руководство оператора: Template/ROP.md
        - Инструкция по сборке: Template/Sborka.md
        - Инструкция по установке: Template/Ustanovka.md
        - Технические условия: Template/TU.md
      - Превью шаблонов конструкторской документации:
        - Программа и методики предварительных испытаний: Template/PMI.md
        - Программа опытной эксплуатации: Template/POE.md
        - Программа и методики приемочных испытаний: Template/PSI.md
  - Git с "нуля", если ты "ноль": 
      - Перед началом знакомства: git/Git-help-do.md
      - Полезная информация: git/Git-help-sprav.md
      - Управление репозиториями: git/Git-help-rep.md
      - Работа с Git: git/Git-help-rab.md
  - Общее об оформлении: Useful.md
  - Библиотека: libs.md
  - Инструменты: Tools.md
  - О людях: about.md

markdown_extensions:
 - pymdownx.superfences
 - attr_list
 - md_in_html
 - admonition
 - pymdownx.details
 - pymdownx.superfences

plugins:
 - glightbox
 - search

extra_css:
  - material-styles.css
