site_name: Справочник полезных знаний
theme:
  name: material
  logo: logo_big3-1.jpg
  favicon: logo_fav.jpg
  language: ru
  features: 
    - navigation.tabs
nav:
  - Главная: index.md
  - ГОСТы: 
    - Общие правила: GOST/GOST-svod.md
    - Оформление по ГОСТ 2, 19, 7.32, 7.0.97: GOST/GOST-srav.md
    - Полезная информация: GOST/GOST-dop.md
  - Шаблоны: 
      - Описание применения: Opisanie-primenenia.md
      - Описание программы: Opisanie-programmi.md
      - Формуляр: Formular.md
  - Git с "нуля", если ты "ноль": 
      - Перед началом знакомства: git/Git-help-do.md
      - Полезная информация: git/Git-help-sprav.md
      - Управление репозиториями: git/Git-help-rep.md
      - Работа с Git: git/Git-help-rab.md
  - Общее об оформлении: Useful.md
  - Библиотека: libs.md
  - Инструменты: Tools.md
  - О людях: about.md

plugins:
 - glightbox

markdown_extensions:
 - pymdownx.superfences
 - attr_list
 - md_in_html
extra_css:
  - material-styles.css
